// Realistic product data for SmartKart
const products = [
  {
    id: 1,
    name: "Quantum X Pro Wireless Earbuds",
    price: 79.99,
    originalPrice: 129.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 2341,
    description: "Experience studio-grade audio with active noise cancellation, 36-hour battery life, and IPX5 water resistance. Equipped with 12mm titanium drivers and Bluetooth 5.3 for seamless connectivity.",
    specs: ["Active Noise Cancellation", "36hr Battery", "IPX5 Waterproof", "Bluetooth 5.3"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 2,
    name: "NexGen 4K Ultra Monitor 32\"",
    price: 449.99,
    originalPrice: 599.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop",
    rating: 4.8,
    reviews: 1892,
    description: "Immersive 32-inch 4K UHD display with 144Hz refresh rate, HDR600, and 1ms response time. Ideal for creative professionals and gamers who demand color accuracy and fluid performance.",
    specs: ["4K UHD", "144Hz", "HDR600", "1ms Response"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 3,
    name: "ThermoWeave Insulated Jacket",
    price: 124.95,
    originalPrice: 189.99,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop",
    rating: 4.4,
    reviews: 876,
    description: "Engineered with graphene-infused insulation for superior warmth-to-weight ratio. Features DWR coating, packable design, and adjustable hood. Perfect for temperatures down to -20°C.",
    specs: ["Graphene Insulated", "DWR Coated", "Packable", "-20°C Rated"],
    inStock: true,
    trending: false,
    featured: true,
  },
  {
    id: 4,
    name: "CyberShield VPN Router",
    price: 199.99,
    originalPrice: 249.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 1543,
    description: "Enterprise-grade VPN router with built-in threat detection, parental controls, and WiFi 6E support. Covers up to 3,500 sq ft with mesh capability and handles 120+ simultaneous devices.",
    specs: ["WiFi 6E", "Built-in VPN", "Threat Detection", "Mesh Ready"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 5,
    name: "Organic Ceylon Green Tea Collection",
    price: 24.99,
    originalPrice: 34.99,
    category: "Groceries",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 3218,
    description: "Premium single-origin Ceylon green tea, hand-picked from high-altitude estates. This curated collection includes 60 biodegradable tea bags in 4 varieties: Pure, Jasmine, Mint, and Citrus.",
    specs: ["60 Tea Bags", "4 Varieties", "Organic Certified", "Biodegradable"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 6,
    name: "ProFit Titan Resistance Bands Set",
    price: 39.99,
    originalPrice: 59.99,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&h=400&fit=crop",
    rating: 4.3,
    reviews: 1672,
    description: "Professional-grade latex resistance bands with 5 resistance levels (10-150 lbs). Includes door anchor, ankle straps, foam handles, and a carrying bag. Perfect for home or travel workouts.",
    specs: ["5 Resistance Levels", "10-150 lbs", "Full Accessory Kit", "Travel Bag"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 7,
    name: "Aurora Mechanical Keyboard RGB",
    price: 149.99,
    originalPrice: 199.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop",
    rating: 4.9,
    reviews: 4521,
    description: "Hot-swappable mechanical keyboard with per-key RGB backlighting, gasket-mount design, and sound-dampening foam layers. Ships with Gateron Pro switches and PBT double-shot keycaps.",
    specs: ["Hot-Swappable", "Gasket Mount", "PBT Keycaps", "Per-Key RGB"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 8,
    name: "Minimalist Leather Crossbody Bag",
    price: 89.99,
    originalPrice: 119.99,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 965,
    description: "Handcrafted from full-grain Italian leather with a slim profile that fits essentials perfectly. Features RFID-blocking pocket, magnetic closure, and adjustable strap. Ages beautifully over time.",
    specs: ["Full-Grain Leather", "RFID Blocking", "Magnetic Closure", "Adjustable Strap"],
    inStock: true,
    trending: true,
    featured: false,
  },
  {
    id: 9,
    name: "SmartBrew Coffee Machine",
    price: 329.99,
    originalPrice: 449.99,
    category: "Home",
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 2876,
    description: "App-controlled espresso machine with built-in grinder, 15-bar pressure, and automatic milk frother. Brew barista-quality coffee from bean to cup with 12 programmable recipes.",
    specs: ["15-Bar Pressure", "Built-in Grinder", "Auto Frother", "12 Recipes"],
    inStock: true,
    trending: false,
    featured: true,
  },
  {
    id: 10,
    name: "HyperDrive 1TB NVMe SSD",
    price: 89.99,
    originalPrice: 129.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400&h=400&fit=crop",
    rating: 4.8,
    reviews: 5632,
    description: "Blazing-fast PCIe Gen4 NVMe SSD with sequential read speeds up to 7,000 MB/s. Features hardware encryption, DRAM cache, and advanced thermal management for sustained performance.",
    specs: ["7,000 MB/s Read", "PCIe Gen4", "Hardware Encryption", "DRAM Cache"],
    inStock: true,
    trending: true,
    featured: false,
  },
  {
    id: 11,
    name: "Bamboo Premium Sushi Making Kit",
    price: 34.99,
    originalPrice: 49.99,
    category: "Groceries",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=400&fit=crop",
    rating: 4.2,
    reviews: 743,
    description: "Complete sushi making kit with bamboo rolling mats, nigiri molds, sashimi knife, chopsticks, and recipe booklet. Made from sustainable bamboo with food-grade materials throughout.",
    specs: ["Bamboo Materials", "Complete Kit", "Recipe Book", "Food-Grade"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 12,
    name: "TrailBlazer Hiking Boots",
    price: 169.99,
    originalPrice: 219.99,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 1234,
    description: "All-terrain hiking boots with Vibram Megagrip outsole, waterproof Gore-Tex membrane, and EVA cushioned midsole. Reinforced toe cap and heel counter for protection on technical trails.",
    specs: ["Vibram Outsole", "Gore-Tex", "EVA Cushion", "Reinforced Toe"],
    inStock: true,
    trending: false,
    featured: true,
  },
  {
    id: 13,
    name: "SilkTouch Wireless Charging Pad",
    price: 29.99,
    originalPrice: 44.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1608751819407-8c8672b1e0b4?w=400&h=400&fit=crop",
    rating: 4.4,
    reviews: 2109,
    description: "Ultra-slim 15W wireless charging pad with alignment magnets and foreign object detection. Compatible with all Qi-enabled devices. Features LED charging indicator and anti-slip base.",
    specs: ["15W Fast Charge", "MagSafe Compatible", "LED Indicator", "Anti-Slip"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 14,
    name: "Urban Flex Slim Fit Chinos",
    price: 59.99,
    originalPrice: 79.99,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=400&fit=crop",
    rating: 4.3,
    reviews: 1456,
    description: "Premium stretch cotton chinos with tailored slim fit. Features hidden flex waistband, reinforced seams, and wrinkle-resistant fabric. Available in 8 colors, from classic navy to stone.",
    specs: ["Stretch Cotton", "Slim Fit", "Wrinkle-Resistant", "8 Colors"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 15,
    name: "AeroGlide Smart Standing Desk",
    price: 599.99,
    originalPrice: 799.99,
    category: "Home",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&h=400&fit=crop",
    rating: 4.8,
    reviews: 987,
    description: "Motorized sit-stand desk with memory presets, anti-collision technology, and cable management tray. Bamboo desktop surface with 70\" width supports up to 300 lbs with whisper-quiet operation.",
    specs: ["Memory Presets", "Anti-Collision", "Bamboo Top", "300 lb Capacity"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 16,
    name: "Precision Chef Knife Set",
    price: 149.99,
    originalPrice: 199.99,
    category: "Home",
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 2341,
    description: "Japanese VG-10 steel knife set with 67-layer Damascus pattern. Includes 8\" chef, 7\" santoku, 5\" utility, and 3.5\" paring knives in a magnetic walnut block. Razor-sharp 15° edge angle.",
    specs: ["VG-10 Steel", "Damascus Pattern", "Walnut Block", "15° Edge"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 17,
    name: "Sentinel Noise-Cancelling Headphones",
    price: 249.99,
    originalPrice: 349.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    rating: 4.8,
    reviews: 3764,
    description: "Over-ear headphones with adaptive noise cancellation that adjusts to your environment in real time. 40mm beryllium drivers deliver audiophile-grade sound across 50 hours of playtime with quick-charge support.",
    specs: ["Adaptive ANC", "50hr Battery", "Beryllium Drivers", "Quick Charge"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 18,
    name: "Vortex Gaming Mouse",
    price: 69.99,
    originalPrice: 99.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 5120,
    description: "Ultra-lightweight 58g gaming mouse with 26K DPI optical sensor, 1000Hz polling rate, and onboard memory for 5 profiles. Honeycomb shell design with PTFE glide feet for zero-friction tracking.",
    specs: ["26K DPI Sensor", "58g Weight", "1000Hz Polling", "5 Profiles"],
    inStock: true,
    trending: true,
    featured: false,
  },
  {
    id: 19,
    name: "Cascade Portable Bluetooth Speaker",
    price: 59.99,
    originalPrice: 89.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 2897,
    description: "360-degree immersive sound with deep bass from dual passive radiators. IP67 waterproof and dustproof with 20-hour battery life. Pairs two speakers for true stereo sound outdoors or indoors.",
    specs: ["360° Sound", "IP67 Rating", "20hr Battery", "Stereo Pairing"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 20,
    name: "NovaPad 11\" Tablet",
    price: 379.99,
    originalPrice: 499.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 1845,
    description: "11-inch Liquid Retina display with 120Hz ProMotion, M2 chip, and all-day battery. Supports stylus input with tilt and pressure sensitivity. Perfect for drawing, note-taking, and media consumption.",
    specs: ["11\" Retina 120Hz", "M2 Chip", "Stylus Support", "All-Day Battery"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 21,
    name: "ZenithWatch Ultra Smartwatch",
    price: 299.99,
    originalPrice: 399.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 4231,
    description: "Titanium-body smartwatch with AMOLED always-on display, dual-band GPS, and advanced health sensors including ECG, SpO2, and skin temperature. 14-day battery with 100m water resistance.",
    specs: ["Titanium Body", "ECG + SpO2", "14-Day Battery", "100m Waterproof"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 22,
    name: "CloudStep Running Shoes",
    price: 139.99,
    originalPrice: 179.99,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 3456,
    description: "Nitrogen-infused foam midsole delivers 15% more energy return than standard EVA. Engineered mesh upper provides breathability and adaptive lockdown. Carbon fiber plate for explosive propulsion.",
    specs: ["Nitrogen Foam", "Carbon Plate", "Engineered Mesh", "15% Energy Return"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 23,
    name: "Apex Yoga Mat Premium",
    price: 49.99,
    originalPrice: 74.99,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
    rating: 4.4,
    reviews: 2134,
    description: "6mm thick natural rubber yoga mat with laser-etched alignment guides. Non-toxic, PVC-free construction with dual-layer grip surface. Includes carrying strap and machine-washable microfiber towel.",
    specs: ["Natural Rubber", "Alignment Guides", "PVC-Free", "6mm Thick"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 24,
    name: "IronCore Adjustable Dumbbell Set",
    price: 299.99,
    originalPrice: 449.99,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop",
    rating: 4.8,
    reviews: 1678,
    description: "Replace 15 pairs of dumbbells with one set. Quick-adjust dial mechanism switches weight from 5 to 52.5 lbs in 2.5 lb increments. Compact design fits any home gym with a durable steel cradle.",
    specs: ["5-52.5 lbs", "Quick Dial Adjust", "Replaces 15 Pairs", "Steel Cradle"],
    inStock: true,
    trending: false,
    featured: true,
  },
  {
    id: 25,
    name: "Summit Cycling Jersey",
    price: 79.99,
    originalPrice: 109.99,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=400&h=400&fit=crop",
    rating: 4.3,
    reviews: 876,
    description: "Aerodynamic race-fit cycling jersey with Italian-milled Lycra fabric and laser-cut ventilation panels. UPF 50+ sun protection, three rear cargo pockets, and reflective elements for low-light visibility.",
    specs: ["Italian Lycra", "UPF 50+", "Laser-Cut Vents", "Reflective Trim"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 26,
    name: "Heritage Wool Overcoat",
    price: 289.99,
    originalPrice: 399.99,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 654,
    description: "Double-breasted overcoat tailored from Italian virgin wool-cashmere blend. Fully lined with Bemberg lining, horn buttons, and functional cuff buttonholes. A timeless investment piece that transcends seasons.",
    specs: ["Wool-Cashmere Blend", "Bemberg Lined", "Horn Buttons", "Italian Fabric"],
    inStock: true,
    trending: false,
    featured: true,
  },
  {
    id: 27,
    name: "Solstice Polarized Sunglasses",
    price: 119.99,
    originalPrice: 159.99,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 2341,
    description: "Handmade acetate frames with premium polarized CR-39 lenses offering 100% UVA/UVB protection. Stainless steel spring hinges for all-day comfort. Includes hard shell case and microfiber cloth.",
    specs: ["Polarized CR-39", "100% UV Protection", "Acetate Frame", "Spring Hinges"],
    inStock: true,
    trending: true,
    featured: false,
  },
  {
    id: 28,
    name: "Canvas Weekender Duffle Bag",
    price: 99.99,
    originalPrice: 139.99,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop",
    rating: 4.4,
    reviews: 1123,
    description: "Waxed canvas duffle with vegetable-tanned leather accents, brass hardware, and a removable shoulder strap. Internal shoe compartment and padded laptop sleeve. Sized for overhead bins at 20 x 11 x 10 inches.",
    specs: ["Waxed Canvas", "Leather Accents", "Shoe Compartment", "Carry-On Size"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 29,
    name: "Midnight Denim Selvedge Jeans",
    price: 148.00,
    originalPrice: 198.00,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 987,
    description: "Japanese selvedge denim woven on vintage shuttle looms in Okayama. Raw indigo with a clean, tapered fit that develops a unique patina over time. Reinforced stitching and copper rivets throughout.",
    specs: ["Japanese Selvedge", "Raw Indigo", "Tapered Fit", "Copper Rivets"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 30,
    name: "Artisan Cold Brew Coffee Kit",
    price: 44.99,
    originalPrice: 64.99,
    category: "Groceries",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 1876,
    description: "All-in-one cold brew system with 1.5L borosilicate glass carafe, dual-mesh stainless filter, and 500g of single-origin Ethiopian Yirgacheffe beans. Brews smooth, low-acid concentrate in 12-24 hours.",
    specs: ["Glass Carafe", "500g Beans Included", "Dual-Mesh Filter", "Low-Acid Brew"],
    inStock: true,
    trending: true,
    featured: false,
  },
  {
    id: 31,
    name: "Harvest Box Organic Snack Crate",
    price: 39.99,
    originalPrice: 54.99,
    category: "Groceries",
    image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&h=400&fit=crop",
    rating: 4.3,
    reviews: 2456,
    description: "Curated selection of 24 organic snacks including dark chocolate bark, roasted almonds, dried mango, trail mix, and granola bars. All USDA Organic certified with no artificial preservatives.",
    specs: ["24 Snacks", "USDA Organic", "No Preservatives", "Curated Selection"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 32,
    name: "Mediterranean Extra Virgin Olive Oil",
    price: 28.99,
    originalPrice: 38.99,
    category: "Groceries",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 3210,
    description: "Cold-pressed from hand-harvested Koroneiki olives in Crete, Greece. Single estate, first cold pressing with fruity aroma and peppery finish. 750ml dark glass bottle to preserve freshness.",
    specs: ["Cold-Pressed", "Single Estate", "Koroneiki Olives", "750ml Bottle"],
    inStock: true,
    trending: false,
    featured: true,
  },
  {
    id: 33,
    name: "Gourmet Spice Collection",
    price: 54.99,
    originalPrice: 74.99,
    category: "Groceries",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 1543,
    description: "18-piece spice collection in handcrafted acacia wood rack. Includes smoked paprika, saffron threads, Madagascar vanilla, Tellicherry peppercorns, and more. Sourced directly from growers worldwide.",
    specs: ["18 Spices", "Acacia Rack", "Globally Sourced", "Saffron Included"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 34,
    name: "Lumina Smart LED Bulb Pack",
    price: 34.99,
    originalPrice: 49.99,
    category: "Home",
    image: "https://images.unsplash.com/photo-1565814329452-e1bc5c035001?w=400&h=400&fit=crop",
    rating: 4.4,
    reviews: 4567,
    description: "Pack of 4 WiFi-enabled smart LED bulbs with 16 million colors and tunable white from warm 2700K to daylight 6500K. Voice control via Alexa and Google Home. Scheduled routines and energy monitoring.",
    specs: ["16M Colors", "WiFi Enabled", "Voice Control", "Energy Monitor"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 35,
    name: "EcoBreeze Air Purifier",
    price: 189.99,
    originalPrice: 259.99,
    category: "Home",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop",
    rating: 4.6,
    reviews: 2341,
    description: "HEPA 13 air purifier for rooms up to 500 sq ft. Captures 99.97% of particles including dust, pollen, smoke, and pet dander. Real-time AQI display, whisper-quiet night mode at 24dB, and auto-speed sensor.",
    specs: ["HEPA 13 Filter", "500 sq ft", "24dB Night Mode", "Real-Time AQI"],
    inStock: true,
    trending: true,
    featured: true,
  },
  {
    id: 36,
    name: "Artisan Ceramic Dinnerware Set",
    price: 129.99,
    originalPrice: 179.99,
    category: "Home",
    image: "https://images.unsplash.com/photo-1603199506016-5d54f78b5777?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 876,
    description: "16-piece handmade stoneware set for 4 with dinner plates, salad plates, bowls, and mugs. Reactive glaze finish ensures each piece is unique. Microwave, dishwasher, and oven safe up to 450°F.",
    specs: ["16 Pieces", "Reactive Glaze", "Handmade Stoneware", "Oven Safe 450°F"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 37,
    name: "Velvet Memory Foam Pillow",
    price: 69.99,
    originalPrice: 99.99,
    category: "Home",
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400&h=400&fit=crop",
    rating: 4.8,
    reviews: 5432,
    description: "Contoured memory foam pillow with cooling gel infusion and ventilated channels. Adjustable loft insert lets you customize height. Removable bamboo-viscose cover is hypoallergenic and machine-washable.",
    specs: ["Cooling Gel", "Adjustable Loft", "Bamboo Cover", "Hypoallergenic"],
    inStock: true,
    trending: false,
    featured: false,
  },
  {
    id: 38,
    name: "ProShot Action Camera 5K",
    price: 279.99,
    originalPrice: 379.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400&h=400&fit=crop",
    rating: 4.7,
    reviews: 3219,
    description: "Ultra-compact action camera shooting 5K at 30fps and 4K at 120fps with HyperSmooth 5.0 stabilization. Waterproof to 33ft without housing, front-facing selfie screen, and voice-activated controls.",
    specs: ["5K 30fps", "HyperSmooth 5.0", "Waterproof 33ft", "Voice Control"],
    inStock: true,
    trending: true,
    featured: false,
  },
  {
    id: 39,
    name: "Nebula Portable Projector",
    price: 349.99,
    originalPrice: 499.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=400&fit=crop",
    rating: 4.5,
    reviews: 1654,
    description: "Pocket-sized 1080p projector with 900 ANSI lumens, Android TV built-in, and auto-keystone correction. Built-in Dolby Audio speakers, 3-hour battery for portable movie nights, and 150\" max projection.",
    specs: ["1080p Native", "900 ANSI Lumens", "Android TV", "3hr Battery"],
    inStock: true,
    trending: false,
    featured: true,
  },
  {
    id: 40,
    name: "FlexFit Smartband Pro",
    price: 49.99,
    originalPrice: 79.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop",
    rating: 4.3,
    reviews: 6789,
    description: "Slim fitness tracker with 1.47\" AMOLED display, continuous heart rate and SpO2 monitoring, sleep tracking, and 110+ sport modes. 14-day battery life with 5ATM water resistance and smartphone notifications.",
    specs: ["AMOLED Display", "110+ Sports", "14-Day Battery", "5ATM Waterproof"],
    inStock: true,
    trending: false,
    featured: false,
  },
];

const categories = [
  { id: 1, name: "Electronics", icon: "cpu", count: 14, color: "#3882f6" },
  { id: 2, name: "Fashion", icon: "shirt", count: 7, color: "#8b5cf6" },
  { id: 3, name: "Groceries", icon: "leaf", count: 6, color: "#22c55e" },
  { id: 4, name: "Sports", icon: "dumbbell", count: 6, color: "#f59e0b" },
  { id: 5, name: "Home", icon: "home", count: 7, color: "#ec4899" },
];

export { products, categories };
